modLoader = "javafml"
loaderVersion = "[47,)"
license = "All Rights Reserved"
[[mods]]
    modId = "kjsindustrialforegoing"
    version = "${file.jarVersion}"
    displayName = "KJS Industrial Foregoing"
    authors = "BobVarioa"
    description = '''

    '''
[[dependencies.kjsindustrialforegoing]]
    modId = "forge"
    mandatory = true
    versionRange = "[47,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.kjsindustrialforegoing]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.kjsindustrialforegoing]]
    modId = "kubejs"
    mandatory = true
    versionRange = "[2001.6.3-build.18,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.kjsindustrialforegoing]]
    modId = "industrialforegoing"
    mandatory = true
    versionRange = "[3.5.7,)"
    ordering = "NONE"
    side = "BOTH"