modLoader = "javafml"
loaderVersion = "[43,)"
license = "All Rights Reserved"
[[mods]]
    modId = "kjsindustrialforegoing"
    version = "${file.jarVersion}"
    displayName = "KJS Industrial Foregoing"
    authors = "BobVarioa"
    description = '''

    '''
[[dependencies.kjsindustrialforegoing]]
    modId = "forge"
    mandatory = true
    versionRange = "[43,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.kjsindustrialforegoing]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.2,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.kjsindustrialforegoing]]
    modId = "kubejs"
    mandatory = true
    versionRange = "[1902.6.1-build.234,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.kjsindustrialforegoing]]
    modId = "industrialforegoing"
    mandatory = true
    versionRange = "[3.3.2.3,)"
    ordering = "NONE"
    side = "BOTH"